# Generated by Django 3.2.1 on 2021-05-10 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_tasklist_manager'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasklist',
            old_name='manager',
            new_name='manage',
        ),
    ]
